language: android
jdk: oraclejdk8

git:
  depth: 3

branches:
  only:
    - master
    - dev


android:
  components:
    - tools
    - android-29
    - platform-tools
    - build-tools-28.0.3


before_install:
  - gradle -b wrapper.gradle wrapper


after_script:
  - cat */build/reports/lint-results.xml


before_cache:
  - rm -f ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/
    - ~/.android/build-cache
